plugins {
    id 'java'
    id("xyz.jpenilla.run-paper") version "2.3.1"
    id("io.papermc.paperweight.userdev") version "2.0.0-beta.18"
    id "com.gradleup.shadow" version "9.0.0-rc3"
}

group = 'org.blackstamp'
version = '1.0.0'

repositories {
    mavenCentral()
    maven{ url = "https://repo.aikar.co/content/groups/aikar/"}
    maven{url = "https://repo.papermc.io/repository/maven-public/"}
    maven{url = "https://oss.sonatype.org/content/groups/public/"}
    maven{url = "https://maven.enginehub.org/repo/"}
    maven{ url = "https://jitpack.io"}
}

dependencies {
    paperweight.paperDevBundle("1.21.5-R0.1-SNAPSHOT")
    implementation("net.dv8tion:JDA:6.0.0-rc.2")

    // FAWE
    implementation("com.intellectualsites.bom:bom-newest:1.52")
    compileOnly("com.fastasyncworldedit:FastAsyncWorldEdit-Core")
    compileOnly("com.fastasyncworldedit:FastAsyncWorldEdit-Bukkit")

    // ACF
    implementation("co.aikar:acf-paper:0.5.1-SNAPSHOT")

    // Kyori Adventure
    implementation("net.kyori:adventure-api:4.20.0")
    implementation("net.kyori:adventure-text-serializer-gson:4.20.0")
    implementation("net.kyori:adventure-platform-bukkit:4.3.4")

    // Reflections
    implementation("com.github.SasuMC:sasu-reflections:1.0")

    // Lombok
    compileOnly("org.projectlombok:lombok:1.18.38")
    annotationProcessor("org.projectlombok:lombok:1.18.38")
}

def targetJavaVersion = 24
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 24

    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        options.release.set(targetJavaVersion)
    }
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset = 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}

shadowJar {
    relocate 'net.dv8tion.jda', 'org.blackstamp.SleepyChronicles.shaded.jda'
    archiveClassifier.set('')
    minimize()

    doLast {
        copy {
            from shadowJar.archiveFile
            into "C:/Users/Martin Godoy/Desktop/misc/server/plugins"
        }
    }
}


tasks {
    runServer {
        minecraftVersion("1.21")
    }

    assemble {
        dependsOn(shadowJar)
    }

    tasks.reobfJar {
        finalizedBy("copyReobfJarToServer")
    }

    tasks.register("copyReobfJarToServer", Copy) {
        from shadowJar
        into "C://Users//Martin Godoy//Desktop//misc//server//plugins"
    }

}